import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Header } from 'components/Header'
import { Footer } from 'components/Footer'
import { Banner } from 'components/atoms/Banner'
import useViewport from 'utils/useViewport'
import { portfolio } from 'config/data'

const inter = Inter({ subsets: ['latin'] })

export default function Page({ data }: any) {
  const { heading, images, banner } = data || {}

  return (
    <>
      <Head>
        <title>{heading}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/icon.svg' />
      </Head>
      <div className=''>
        <Header />

        <Banner image={banner} heading={heading} description='A collection of stories' />

        <div className='container py-[40px] md:py-[60px] flex justify-center items-center'>
          <div className='flex flex-col md:grid md:grid-cols-2 lg:grid-cols-4 grid-flow-row-dense gap-[24px]'>
            {images?.map((image: any, index: number) => {
              const { type, url } = image || {}

              switch (type) {
                case 'portrait':
                  return (
                    <div className='portrait' data-aos='zoom-in' data-aos-duration='400'>
                      <Image
                        width={300}
                        height={600}
                        key={index}
                        src={url}
                        alt={`Image ${index} of ${heading} album`}
                        className='w-full h-[400px] md:w-[300px] object-cover object-center'
                      />
                    </div>
                  )
                case 'landscape':
                  return (
                    <div
                      className='landscape col-span-2'
                      data-aos='zoom-in'
                      data-aos-duration='400'>
                      <Image
                        width={600}
                        height={400}
                        key={index}
                        src={url}
                        alt={`Image ${index} of ${heading} album`}
                        className='w-full lg:w-[600px] h-[400px] object-cover object-center'
                      />
                    </div>
                  )
                default:
                  return (
                    <div className='other'>
                      <h2>Other</h2>
                      <Image
                        width={200}
                        height={600}
                        key={index}
                        src={url}
                        alt={`Image ${index} of ${heading} album`}
                      />
                    </div>
                  )
              }
            })}
          </div>
        </div>

        <Footer />
      </div>
    </>
  )
}

export const getStaticProps = (context: any) => {
  /* Get slug from URL */
  const slug = context?.params?.slug

  /* Filter object related to the slug from data array */
  const dataObject = portfolio?.filter((item: any) => {
    if (item?.slug === slug) {
      return item
    }
  })[0]

  /* Return page props with data */
  return {
    props: {
      data: dataObject || {},
    },
  }
}

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: true,
  }
}
