/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Header } from 'components/Header'
import { Carousel } from 'components/Carousel'
import { OurServices } from 'components/OurServices'
import { Footer } from 'components/Footer'
import { Banner } from 'components/atoms/Banner'
import { ServiceDescriptionImages } from 'components/ServiceDescriptionImages'
import { Button } from 'components/Button'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/icon.svg' />
      </Head>
      <div className=''>
        <Header />

        <Banner
          image='/carousel/3.webp'
          heading='Let us tell about our journey'
          description='A collection of stories'
        />

        <div className='container py-[40px] md:pt-[80px] md:pb-[100px] flex flex-col items-center'>
          <h1 className='text-h3 font-heading font-600 lg:text-display-sm text-N-500 uppercase text-center w-[82%] md:w-full'>
            About us
          </h1>
          <p className='text-base text-N-600 lg:w-[960px]'>
            At Meliora Lifestyle, we see the world through a lens, and it is a beautiful place. We
            are a team of creative individuals who specialize in capturing life's most precious
            moments and turning them into art.
            <br />
            <br />
            We believe that a photograph is not just a picture but a portal to a memory, a feeling,
            and a time. Our goal is to preserve the essence of your special day in works of art that
            you will cherish forever. Each photo is a unique piece of art, a window to a memory,
            feeling, and time. With years of expertise and a passion for excellence, we are
            confident in our ability to create lasting memories for you.
            <br />
            <br />
            We understand the importance of capturing memories that will last a lifetime and that is
            why we approach each photo session with care and dedication. Our team of experienced
            photographers use their creative vision to create stunning, timeless images that you
            will treasure for years to come. Whether you are looking for stunning wedding
            photography, pre-shoot, or your special event coverage, our goal is to exceed your
            expectations. So, let us help you tell your story and create memories that will last a
            lifetime.
          </p>

          <div className='pt-[32px] md:pt-[56px]'>
            <Link href='/contact'>
              <Button appearance='primary' label='Contact us' />
            </Link>
          </div>
        </div>

        <Footer />
      </div>
    </>
  )
}
