import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Header } from 'components/Header'
import { Footer } from 'components/Footer'
import { Banner } from 'components/atoms/Banner'
import { SectionHeading } from 'components/atoms/SectionHeading'

const inter = Inter({ subsets: ['latin'] })

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/icon.svg' />
      </Head>
      <div className=''>
        <Header />

        <Banner
          image='/carousel/8.webp'
          heading='We love hearing from you'
          description='A collection of stories'
        />

        <div className='flex justify-center pt-[32px] md:pt-[60px]'>
          <SectionHeading
            heading='Contact us'
            description='At Meliora Lifestyle, we love engaging with new ideas. If you have any inquiry about upcoming events please
                get in touch with us through below contact information.'
          />
        </div>

        <div className='container pb-[40px] md:pb-[100px] flex flex-col items-center lg:w-[960px] pt-[32px] lg:pt-[60px]'>
          <div className='md:grid md:grid-cols-2 flex flex-col gap-y-[16px] md:gap-x-[40px] lg:gap-x-[80px] md:gap-y-[32px]'>
            {/* Call */}
            <div className='flex flex-col'>
              <div className='flex items-center gap-[12px]'>
                <i className='ri-phone-line text-N-600 text-[24px]' />
                <p className='text-h6 font-heading uppercase font-600 text-N-600'>Call us</p>
              </div>
              <p className='text-base text-N-600 pt-[12px]'>Ruwin Lakshitha : +94 77 71 30 572</p>
            </div>
            {/* Whatsapp */}
            <div className='flex flex-col'>
              <a href='https://wa.me/94777130572' data-action='share/whatsapp/share'>
                <div className='flex items-center gap-[12px]'>
                  <i className='ri-whatsapp-line text-N-600 text-[24px]' />
                  <p className='text-h6 font-heading uppercase font-600 text-N-600 hover:text-B-800'>Whatsapp us</p>
                </div>
                <p className='text-base text-N-600 pt-[12px] hover:text-B-800'> +94 77 71 30 572</p>
              </a>
            </div>
            {/* email */}
            <div className='flex flex-col gap-[12px] md:pt-[24px]'>
              <div className='flex items-center gap-[12px]'>
                <i className='ri-mail-line text-N-600 text-[24px]' />
                <p className='text-h6 font-heading uppercase font-600 text-N-600'>Write us</p>
              </div>
              <a
                href='mailto:melioralifestyleweddings@gmail.com'
                rel='noreferrer'
                className='text-base text-N-600 flex items-center gap-[12px] hover:text-B-800'>
                melioralifestyleweddings@gmail.com
              </a>
              <a
                href='mailto:melioralifestyleweddings@gmail.com'
                rel='noreferrer'
                className='text-base text-N-600 flex items-center gap-[12px] hover:text-B-800'>
                hellomelioralifestyle@gmail.com
              </a>
            </div>
            {/* Location */}
            <div className='md:pt-[24px]'>
              <div className='flex items-center gap-[12px]'>
                <i className='ri-map-pin-line text-N-600 text-[24px]' />
                <p className='text-h6 font-heading uppercase font-600 text-N-600'>Location</p>
              </div>
              <p className='text-base text-N-600 pt-[12px]'>Matara, Sri Lanka.</p>
              <p className='text-base text-N-600 pt-[12px]'>Colombo, Sri Lanka.</p>
            </div>
          </div>
        </div>

        <Footer />
      </div>
    </>
  )
}
